language: go
go:
 - 1.13.8


script:
  - tree
  - go version
  - go get github.com/stretchr/testify
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test test/guest_test.go
