sudo: required
dist: focal

before_install:
  - sudo apt-get update -qq

install:
  - tar -C /usr/local -xzf go1.14.3.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - go version
  - go get github.com/stretchr/testify
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - tree
  - go test test/guest_test.go

after_success:
  - echo "TODO"
