sudo: required
dist: focal

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install golang
  - go get github.com/stretchr/testify
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - tree
  - go test test/guest_test.go

after_success:
  - echo "TODO"
